### ISSUE TITLE
mtcnn 错误

### ISSUE THREAD

**Issue by duoduo1018** [zuoqing1988/ZQCNN#49]
您好,非常感谢您的分享.  我现在进行mtcnn 训练,  遇到了错误

F:\train-mtcnn-head>set MXNET_CUDNN_AUTOTUNE_DEFAULT=0

F:\train-mtcnn-head>python example\train_P_net20.py --gpus 0 --lr 0.
001 --image_set train_20_1 --prefix model/pnet20 --end_epoch 16 --lr_epoch 8,14
--frequent 10 --batch_size 1000 --thread_num 24
D:\ProgramData\Anaconda2\lib\site-packages\urllib3\contrib\pyopenssl.py:46: Depr
ecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL
Called with argument:
Namespace(batch_size=1000, begin_epoch=0, dataset_path='data/mtcnn', end_epoch=1
6, epoch=0, frequent=10, gpu_ids='0', image_set='train_20_1', lr=0.001, lr_epoch
='8,14', prefix='model/pnet20', pretrained='model/pnet20', resume=False, root_pa
th='data', thread_num=24)
init weights and bias:
hello3
F:\train-mtcnn-head\example\train.py:38: DeprecationWarning: [91mCa
lling initializer with init(str, NDArray) has been deprecated.please use init(mx
.init.InitDesc(...), NDArray) instead.[0m
  init(k, args[k])
F:\train-mtcnn-head\example\train.py:55: DeprecationWarning: [91mCa
lling initializer with init(str, NDArray) has been deprecated.please use init(mx
.init.InitDesc(...), NDArray) instead.[0m
  init(k, auxs[k])
lr 0.001 lr_epoch [8, 14] lr_epoch_diff [8, 14]
Traceback (most recent call last):
  File "example\train_P_net20.py", line 62, in <module>
    args.begin_epoch, args.end_epoch, args.batch_size, args.thread_num, args.fre
quent, args.lr, lr_epoch, args.resume)
  File "example\train_P_net20.py", line 17, in train_P_net20
    20, True, True, frequent, not resume, lr, lr_epoch)
  File "F:\train-mtcnn-head\example\train.py", line 90, in train_net

    arg_params=args, aux_params=auxs, begin_epoch=begin_epoch, num_epoch=end_epo
ch)
  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\base_module.py",
 line 460, in fit
    for_training=True, force_rebind=force_rebind)
  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\module.py", line
 429, in bind
    state_names=self._state_names)
  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\executor_group.p
y", line 265, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\executor_group.p
y", line 361, in bind_exec
    shared_group))
  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\executor_group.p
y", line 639, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "D:\ProgramData\Anaconda2\lib\site-packages\mxnet\symbol\symbol.py", line
 1518, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1000, 3L, 20L, 20L)
bbox_target: (1000, 4L)
label: (1000,)
[14:26:44] C:\projects\mxnet-distro-win\mxnet-build\src\storage\storage.cc:125:
Compile with USE_CUDA=1 to enable GPU usage

这个错误您遇到过吗?  是不是mxnet版本不对呢?

**Comment by duoduo1018** [comment]
已经解决了, 得安装GPU version ,  pip install mxnet-cu8.0
